### ISSUE TITLE
Dependabot Not Working

### ISSUE THREAD

**Issue by gxrsti** [gxrsti/alert#1]
Dependabot is not working in this project, and the issue may be related to our use of pnpm and workspaces.

**Expected Behavior:**

Dependabot should submit prs to update dependencies for `root` and `website` directory when new versions are available.

**Current Behavior:** 

Dependabot is not detecting or updating dependencies, it also doesn't provide errors.

**Comment by luc122c** [comment]
According to [this blog post](https://github.blog/changelog/2023-06-12-dependabot-version-updates-now-supports-pnpm/):

> At this time, Dependabot will not open security alerts against pnpm dependencies

I'll open a PR to also check the `website` directory for you.

**Comment by gxrsti** [comment]
Hey @luc122c, thanks for contributing!

Let's see if this works, I will merge the changes.

**Comment by gxrsti** [comment]
Looks like it's still not working. Do you know how if it takes some time until the next check is initiated?

**Comment by luc122c** [comment]
Hmm, it's only been a couple of days, perhaps your lockfile is upto date and there have been no further updates?

**Comment by gxrsti** [comment]
Hmm, for example typescript is on version 4.x, but the latest is 5.x so I don't think it is up to date. If I look into the dependency graph under insights I also don't see any watched files by dependabot.

**Comment by luc122c** [comment]
> According to [this blog post](https://github.blog/changelog/2023-06-12-dependabot-version-updates-now-supports-pnpm/):
> 
> > At this time, Dependabot will not open security alerts against pnpm dependencies

It looks like that was out of date and [PNPM should now be fully supported](https://github.blog/changelog/2023-08-02-pnpm-support-for-dependency-graph-dependabot-alerts-and-dependabot-security-updates/). Perhaps there's something else going on. Does the dependency graph show anything for you?

**Comment by gxrsti** [comment]
Nope, is says "Dependabot version updates aren't configured yet"

**Comment by Hackerbone** [comment]
Dependabot generally scans once a week (In my experience). So it should technically reflect update PRs sometime this week.

**Comment by gxrsti** [comment]
Dependabot scans on a daily basis if the interval is set to daily. If the configuration changes, it should immediately check the dependencies so there still seems to be a problem. I will take a look at this tomorrow or monday.

**Comment by gxrsti** [comment]
To keep this issue updated:
I asked dependabot team what the issue could be and they told me that it seems like dependabot ran into a problem when first enabled on my account and that I should open a support ticket on github.

I hope this gets resolved quickly. [Here](https://github.com/dependabot/dependabot-core/issues/8260#event-10758816801) is the conversation if anyone is interested.

**Comment by gxrsti** [comment]
I didn't get a reply, but suddenly Dependabot seems to be working in all my repositories, which leads me to believe that something has happened on github's end. I will close this issue, thank you all for your help!
