### ISSUE TITLE
Props do not work

### ISSUE THREAD

**Issue by nadirozsoy** [gxrsti/alert#103]
position,style... 
none of them work properly

**Comment by gxrsti** [comment]
Hey @nadirozsoy,

I just released version 6.0.2 which fixes problems with the toaster position and adds the `options` property to the `<Toaster/>` component. Via `options` you are able to set `className` and `style` for all toasts or you can explicitly set those properties for the different types of toasts like this:

`<Toaster
options={{ success: { className: "class", style: { backgroundColor: "red" }}}}
/>`

Hope this meets your expecations, will close this issue now. Feel free to reopen!
