### ISSUE TITLE
Allow Changing Direction Of Toasts 

### ISSUE THREAD

**Issue by gxrsti** [gxrsti/alert#12]
A new property called `reverse` should be added to the <Toaster/> component. It should toggle the direction of the toasts. Normally toasts should add to the bottom. If reverse is true, toasts should be added to the top.

Additionally, please add a toggle to the demo website which allows users to toggle the direction!

**Comment by AdityaNik** [comment]
hii @gxrsti can you please just elaborate about the reverse property and toggle direction of toast.

**Comment by mjubair** [comment]
Hi @gxrsti I have raised a PR for this issue. hope this helps https://github.com/gxrsti/alert/pull/16
