### ISSUE TITLE
Write Comments For Better Code Documentation

### ISSUE THREAD

**Issue by gxrsti** [gxrsti/alert#18]
Effective code comments are essential for understanding and maintaining the codebase. Also users get an brief explanation of what a function does. 

This issue aims to improve the codebase's readability and maintainability by adding code comments.

Example: 

![image](https://github.com/gxrsti/alert/assets/88879471/d7e589d9-6fc4-4122-a013-254ef041c452)

**Comment by shakthi2003-ice** [comment]
@gxrsti  can you assign me this issue?

**Comment by gxrsti** [comment]
Sure, here you go!

**Comment by gxrsti** [comment]
Currently, there are no comments. We need comments at least for all the exported Components/Functions!

The more, the better.

**Comment by shakthi2003-ice** [comment]
@gxrsti we should we add the toaster component?

**Comment by gxrsti** [comment]
> @gxrsti we should we add the toaster component?

Toaster component and toast function at least.

**Comment by shakthi2003-ice** [comment]
@gxrsti  while running ppm run development website I am getting this error

Turborepo requires npm workspaces to be defined in the root package.json

**Comment by gxrsti** [comment]
@shakthi2003-ice Try these steps in the project root:

1. Run `pnpm install`
2. Run `pnpm run dev:website`

**Comment by shakthi2003-ice** [comment]
@gxrsti i did the same but still getting error

**Comment by gxrsti** [comment]
Make sure to have the newest version of the master branch. 

If you follow [these steps](https://github.com/gxrsti/alert/blob/master/CONTRIBUTING.md#development), everything should work.

Also make sure to have pnpm installed (`npm install -g pnpm`)

**Comment by gxrsti** [comment]
@shakthi2003-ice did you get it working?

**Comment by gxrsti** [comment]
Hey @Moksh45-Bot!

For file changes, could you please open a pr? Also from what i see, i would like to use [this](https://user-images.githubusercontent.com/88879471/275842991-d7e589d9-6fc4-4122-a013-254ef041c452.png) commenting style as far as it is possible to also descripe the parameters of a function or component.

**Comment by Moksh45** [comment]
@gxrsti ok

**Comment by gxrsti** [comment]
Will close this issue since #36 was created and this issue has a lot of irrelevant comments.
