### ISSUE TITLE
Add `toast.promise()` function

### ISSUE THREAD

**Issue by gxrsti** [gxrsti/alert#19]
Similar to `toast.success()` or `toast.error()` we need an option to create a toast which shows a loading indicator while the promise is pending and success or error based on if the promise was fulfilled or rejected.

Here is an example how the function should work: 

```
const promise = () => new Promise((resolve) => setTimeout(resolve, 2000));

toast.promise(promise, {
  loading: 'Loading...',
  success: 'Success',
  error: 'Error',
});
```

**Comment by sagarxjadhav** [comment]
@gxrsti can you assign this to me i can solve this!!!

**Comment by gxrsti** [comment]
> @gxrsti can you assign this to me i can solve this!!!

Sure, here you go!

**Comment by gxrsti** [comment]
Hey @sagarxjadhav! Are you still working on this or can i remove you from the Assignees?

**Comment by Hackerbone** [comment]
I can work on this if it's stale
