### ISSUE TITLE
Add Build and Test Workflow

### ISSUE THREAD

**Issue by gxrsti** [gxrsti/alert#2]
We currently do not have workflows set up for this library when pull requests are opened. Establishing automated workflows will improve our development process and ensure code quality.

For now a simple build and test check would be enough. If you have any other ideas feel free to suggest/implement them.

**Comment by Hackerbone** [comment]
I'd like to work on this issue!

**Comment by gxrsti** [comment]
Sure, here you go @Hackerbone
