### ISSUE TITLE
Add Light/Dark Mode To Demo Website

### ISSUE THREAD

**Issue by gxrsti** [gxrsti/alert#21]
Shadcn/ui offers theming through their ThemeProvider [here](https://ui.shadcn.com/docs/dark-mode/next).

This should be added to our demo website with a toggle to switch the themes.
Default should be "system".

**Comment by Shashi3k** [comment]
hey gxrsti i have added  the light.dark mode. pleasse accept m pull request. This is my first time participating hacktoberfest. I really need this
