### ISSUE TITLE
Design Icon/Logo For This Package

### ISSUE THREAD

**Issue by gxrsti** [gxrsti/alert#23]
Perhaps there is a talented and creative person here who could design a minimalist icon for this package – your help would be highly greatly appreciated!

I am open for anything!

**Comment by Kabiirk** [comment]
Hi @gxrsti,

Can I work on this ?

Let me know :
1. If the logo I submitted in my `dem.fig` for for Issue #13 should suffice for this ?
2. What are the requirements for the Icon ?
3. What are the expected files ?

best regards,
Kabiir

**Comment by gxrsti** [comment]
Hey @Kabiirk, 
sure! Basically i want something small that could work out as a favicon. It should contain the '!' since we used it in `A!ert`.
Also i would like to keep it in the black/white style. `svg`, `png` and `ico` files would be amazing.
It can be circled background or a rounded rectangle, we will need to see what fits best.

Here are some examples (second one is something AI generated but i liked the round style):

- https://react-hot-toast.com/favicon.png
- ![DreamShaper_v7_A_sleek_and_modern_notification_bell_icon_in_2D_3](https://github.com/gxrsti/alert/assets/88879471/efa303a7-ea42-4a71-b269-3bc0824dc051)
- ![discotools-xyz-icon (2)](https://github.com/gxrsti/alert/assets/88879471/1091540a-8d29-465d-910f-2603f21cef3b)

**Comment by Kabiirk** [comment]
Great !

Let me come up with something !

**Comment by gxrsti** [comment]
Resolved by #39
