### ISSUE TITLE
Add Footer To Website

### ISSUE THREAD

**Issue by gxrsti** [gxrsti/alert#25]
We need a very simple footer for the demo website. 

It should look something like this: 

![image](https://github.com/gxrsti/alert/assets/88879471/5c397e04-9161-4700-9e4f-024e90a074a1)

"Gersti" should be a link to my github profile, the github link should point to this repo.

**Comment by sid172014** [comment]
Hey @gxrsti i hope you're doing good , can you please assign me this issue?

**Comment by gxrsti** [comment]
Hey @sid172014, here you go!

**Comment by gxrsti** [comment]
resolved by 60f4584
