### ISSUE TITLE
Add Install Instructions To Website

### ISSUE THREAD

**Issue by gxrsti** [gxrsti/alert#26]
We need a section which shows how to install the package.

Something like `npm install alert`, `yarn install alert` and so on. Feel free to get inspiration from other packages.

**Comment by Anjali-Kedia** [comment]
@gxrsti I would like to work on this issue

**Comment by gxrsti** [comment]
Hey @Anjali-Kedia, sure here you go!

**Comment by Anjali-Kedia** [comment]
@gxrsti I have added a PR for the same, do let me know for any changes!

**Comment by gxrsti** [comment]
Resolved by b602dfc
