### ISSUE TITLE
Improve Feature Showcase Of Website

### ISSUE THREAD

**Issue by gxrsti** [gxrsti/alert#27]
Currently, the demo website is just some buttons and selects. We need an actual landing page, a layout, some text and to showcase the features including code snippets.

This is not a concrete issue, feel free to improve it as you would like to. I'm open for anything and will give feedback!

**Comment by Shrest4647** [comment]
Hi @gxrsti . I would like to work on this issue.

**Comment by gxrsti** [comment]
Hey @Shrest4647! Sure, i assigned this issue to you!

**Comment by gxrsti** [comment]
This issue will be closed since I will take this into my own hands.
