### ISSUE TITLE
Add Copy Button To Codeblocks On Website

### ISSUE THREAD

**Issue by gxrsti** [gxrsti/alert#28]
The `<Codeblock/>` component needs an icon button to copy the code to the clipboard.

I would suggest to put it in the top right corner of an codeblock!

**Comment by AniketNS** [comment]
Hey, Assign this issue to me

**Comment by gxrsti** [comment]
Hey @AniketNS, sure here you go!

**Comment by AniketNS** [comment]
Hey @gxrsti, Will you please tell me how to run the project? I don't know where to add that toaster component.

**Comment by gxrsti** [comment]
Hey @AniketNS, to run the project locally please follow the Development instructions [here](https://github.com/gxrsti/alert/blob/master/CONTRIBUTING.md).

If you still have any questions feel free to reach out!

**Comment by gxrsti** [comment]
Resolved by 067517b
