### ISSUE TITLE
`Position` Property doesn't affect `Toaster` Component

### ISSUE THREAD

**Issue by gxrsti** [gxrsti/alert#4]
The `position` property can currently be provided to the `Toaster` component, but it does not have any impact on the positioning of toasts. 

It should change the placement of the `Toaster`. Animations and directions of the toasts inside can be ignored for now.

**Comment by AksBad007** [comment]
Hi, if this is still is open, I'd like to be assigned.

**Comment by gxrsti** [comment]
Hey, sure!
